package net.nthakur.model;
import com.nthakur.Someone;

dialect "mvel"

import java.util.LinkedList;
global String str

// --------------------------------------------------------------

rule "who is a perv"
  when
    Someone($name:name, age < 70)
  then
	System.out.println($name + " loves whicker baskets")
end

rule "who is young"
  when
    Someone($name:name, age < 30)
  then
	System.out.println($name + str)
    System.out.println($name+" is very young")
end

